#服务注册中心配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
  instance:
    appname: api-gateway-zuul

#设置网关端口号
server:
  port: 8080

spring:
  application:
    name: api-gateway-zuul

